name: Release
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  tagpr:
    permissions:
      actions: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
    - uses: Songmu/tagpr@43d52e123cf8d55db9d602601f115f530588e2f8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: tagpr
    if: needs.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Publish
      run: |
        npm install
        npm install --global @vscode/vsce
        vsce publish --baseImagesUrl https://raw.githubusercontent.com/ono-max/vscode-launchable/main
      env:
        # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
