name: tagpr
on:
  push:
    branches:
    - main
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
    - uses: Songmu/tagpr@43d52e123cf8d55db9d602601f115f530588e2f8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
